package main

import (
	"fmt"

	"github.com/mattermost/mattermost/server/public/model"
)

// handleRules points users at the shipped sample Prometheus alerting rules —
// a browsable HTML view and the raw file to download. This is the upstream
// half of the pipeline the plugin does NOT own: the plugin creates the
// Alertmanager receivers and routes, but SOMETHING in the user's Prometheus
// has to emit alerts carrying the `runbook:` label. This command hands them a
// ready starting set so they don't have to go dig it out of the repo.
//
// The files are served from the plugin's public/ assets (generated by
// build/render-docs from samples/prometheus-rules.yaml), so there's no server
// state to read — just the two URLs derived from SiteURL.
func (p *Plugin) handleRules(args *model.CommandArgs) (string, error) {
	base := fmt.Sprintf("%s/plugins/%s/public/help", p.siteURL(), Manifest.Id)
	viewURL := base + "/prometheus-rules.html"
	rawURL := base + "/prometheus-rules.yaml"

	return fmt.Sprintf(
		"**Sample Prometheus alerting rules** — the upstream half of the pipeline.\n\n"+
			"The plugin creates the Alertmanager receivers and routes, but your **Prometheus** has to emit the alerts that carry the `runbook:` label. These samples give you one working rule for every runbook (31 rules across 30 runbooks) so you don't start from a blank page.\n\n"+
			"- 📖 [View the rules in your browser](%s)\n"+
			"- ⬇ [Download `prometheus-rules.yaml`](%s) — add it to your Prometheus `rule_files:` glob, or wrap the `groups:` block in a `PrometheusRule` CRD if you run the Prometheus Operator\n\n"+
			"⚠️ Every threshold is a demo-cluster placeholder — tune to your traffic and SLOs before production. The `runbook:` label on each rule is the join key that routes it to the matching runbook in chat.",
		viewURL, rawURL,
	), nil
}
